spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/book_database
    password: Adeshola081
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      springframework: DEBUG
